# This is a basic workflow to help you get started with Actions

name: refresh_readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  on:
    schedule:
    - cron: "*/30 * * * * " # Runs every half hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  refresh_readme:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@master

    - name: Install pandoc and pandoc citeproc
      run: |
        brew install pandoc
        brew install pandoc-citeproc
    
    - name: Cache Renv packages
      uses: actions/cache@v1
      with:
        path: $HOME/.local/share/renv
        key: r-${{ hashFiles('renv.lock') }}
        restore-keys: r-

    - name: Install packages
      run: |
        R -e 'install.packages("renv")'
        R -e 'renv::restore()'

    - name: Compile the readme
      run: |
        echo Compiling the new readme.
        R -e "rmarkdown::render('README.Rmd')"
        echo Pushing it to github??
